from dataclasses import dataclass, field
from datetime import date, timedelta, time as Time
from typing import Optional


@dataclass
class Task:
    """Single pet care activity."""
    task_id: int
    pet_id: int             # links task to a specific Pet
    title: str
    task_type: str          # walk | feeding | meds | grooming | enrichment | appointment
    description: str        # longer detail about the activity
    duration: int           # minutes
    task_date: date
    task_time: Time
    priority: int
    frequency: str = "once" # once | daily | weekly — how often task repeats
    status: str = "pending" # pending | completed | skipped
    notes: str = ""
    required: bool = False  # if True, always included regardless of time budget (#5)

    def mark_complete(self) -> None:
        self.status = "completed"

    def mark_skipped(self) -> None:
        self.status = "skipped"


@dataclass
class Pet:
    """Stores pet profile and owns that pet's task list."""
    pet_id: int
    pet_name: str
    species: str
    breed: str
    pet_dob: date
    weight: float = 0.0
    medical_notes: str = ""
    tasks: list[Task] = field(default_factory=list)

    def get_age(self) -> int:
        """Return pet's age in whole years, correctly handling leap years. (#2)"""
        today = date.today()
        age = today.year - self.pet_dob.year
        if (today.month, today.day) < (self.pet_dob.month, self.pet_dob.day):
            age -= 1
        return age

    def get_tasks(self, filter_date: Optional[date] = None) -> list[Task]:
        """Return tasks for this pet, optionally filtered by date. (#9)"""
        if filter_date is None:
            return self.tasks
        return [t for t in self.tasks if t.task_date == filter_date]


class Owner:
    """Manages multiple pets; aggregates tasks across all of them."""
    def __init__(
        self,
        owner_id: int,
        name: str,
        available_time: int,        # minutes per day
        preferences: Optional[list] = None,
    ):
        self.owner_id = owner_id
        self.name = name
        self.available_time = available_time
        self.preferences: list = preferences or []
        self.pets: list[Pet] = []
        self._pet_index: dict[int, Pet] = {}  # O(1) lookup (#1)
        self._last_plan: list[Task] = []

    def add_pet(self, pet: Pet) -> None:
        self.pets.append(pet)
        self._pet_index[pet.pet_id] = pet

    def edit_pet(self, pet_id: int, updates: dict) -> None:
        """Update attributes of an existing pet by ID. (#6)"""
        pet = self.get_pet(pet_id)
        if pet:
            for key, value in updates.items():
                setattr(pet, key, value)

    def get_pet(self, pet_id: int) -> Optional[Pet]:
        """O(1) pet lookup via index. (#1)"""
        return self._pet_index.get(pet_id)

    def remove_pet(self, pet_id: int) -> None:
        self.pets = [p for p in self.pets if p.pet_id != pet_id]
        self._pet_index.pop(pet_id, None)

    def add_task(self, task: Task) -> None:
        """Add a task to the correct pet's task list using task.pet_id."""
        pet = self.get_pet(task.pet_id)
        if pet:
            pet.tasks.append(task)

    def edit_task(self, task_id: int, updates: dict) -> None:
        """Update attributes of an existing task by ID. (#6)"""
        for task in self.get_tasks():
            if task.task_id == task_id:
                for key, value in updates.items():
                    setattr(task, key, value)
                return

    def remove_task(self, task_id: int) -> None:
        """Remove a task from its pet's task list by ID. (#6)"""
        for pet in self.pets:
            pet.tasks = [t for t in pet.tasks if t.task_id != task_id]

    def get_tasks(self) -> list[Task]:
        """Return all tasks across every pet owned."""
        return [task for pet in self.pets for task in pet.tasks]

    def get_schedule(self) -> list[Task]:
        """Return the last daily plan generated by the Scheduler. (#8)"""
        return self._last_plan


class Scheduler:
    """Brain: retrieves, organizes, and manages tasks across all pets."""
    def __init__(self, owner: Owner, schedule_date: date):
        self.owner = owner
        self.schedule_date = schedule_date
        self.daily_plan: list[Task] = []
        self.conflicts: list[tuple[Task, Task]] = []

    def get_tasks_for_pet(self, pet_id: int) -> list[Task]:
        """Return all tasks belonging to a single pet."""
        return [t for t in self.owner.get_tasks() if t.pet_id == pet_id]

    def get_tasks_for_date(self, target: date) -> list[Task]:
        """Return all tasks scheduled on a specific date."""
        return [t for t in self.owner.get_tasks() if t.task_date == target]

    def prioritize_tasks(self) -> list[Task]:
        """Sort today's tasks by priority descending, then by time ascending."""
        today_tasks = self.get_tasks_for_date(self.schedule_date)
        return sorted(today_tasks, key=lambda t: (-t.priority, t.task_time))

    def detect_conflicts(self, tasks: list[Task]) -> list[tuple[Task, Task]]:
        """Return pairs of tasks whose scheduled times overlap. (#4)"""
        sorted_tasks = sorted(tasks, key=lambda t: t.task_time)
        conflicts = []
        for i in range(len(sorted_tasks) - 1):
            a, b = sorted_tasks[i], sorted_tasks[i + 1]
            a_end_min = a.task_time.hour * 60 + a.task_time.minute + a.duration
            b_start_min = b.task_time.hour * 60 + b.task_time.minute
            if a_end_min > b_start_min:
                conflicts.append((a, b))
        return conflicts

    def generate_plan(self) -> list[Task]:
        """
        Fit tasks into the owner's time budget.
        Required tasks (e.g. meds) are always included first. (#5)
        Optional tasks fill remaining budget by priority/time order. (#3)
        Detects time conflicts in the final plan. (#4)
        """
        plan = []
        time_used = 0
        tasks = self.prioritize_tasks()

        required = [t for t in tasks if t.required]
        optional = [t for t in tasks if not t.required]

        for task in required:
            plan.append(task)
            time_used += task.duration

        for task in optional:
            if time_used + task.duration <= self.owner.available_time:
                plan.append(task)
                time_used += task.duration

        plan.sort(key=lambda t: t.task_time)
        self.conflicts = self.detect_conflicts(plan)
        self.daily_plan = plan
        self.owner._last_plan = plan  # wire get_schedule (#8)
        return plan

    def expand_recurring(self, days: int = 7) -> list[Task]:
        """Clone recurring tasks forward for the next N days. (#7)"""
        new_tasks = []
        base_id = max((t.task_id for t in self.owner.get_tasks()), default=0) + 1

        for task in self.owner.get_tasks():
            if task.frequency == "daily":
                for d in range(1, days + 1):
                    new_tasks.append(Task(
                        task_id=base_id,
                        pet_id=task.pet_id,
                        title=task.title,
                        task_type=task.task_type,
                        description=task.description,
                        duration=task.duration,
                        task_date=task.task_date + timedelta(days=d),
                        task_time=task.task_time,
                        priority=task.priority,
                        frequency=task.frequency,
                        required=task.required,
                        notes=task.notes,
                    ))
                    base_id += 1
            elif task.frequency == "weekly":
                new_tasks.append(Task(
                    task_id=base_id,
                    pet_id=task.pet_id,
                    title=task.title,
                    task_type=task.task_type,
                    description=task.description,
                    duration=task.duration,
                    task_date=task.task_date + timedelta(weeks=1),
                    task_time=task.task_time,
                    priority=task.priority,
                    frequency=task.frequency,
                    required=task.required,
                    notes=task.notes,
                ))
                base_id += 1

        return new_tasks

    def notify(self, message: str) -> None:
        """Send a notification message to the owner."""
        pass

    def explain_plan(self) -> str:
        """Return a human-readable summary of the generated plan."""
        required_count = sum(1 for t in self.daily_plan if t.required)
        optional_count = len(self.daily_plan) - required_count
        total_min = sum(t.duration for t in self.daily_plan)
        lines = [
            f"Plan: {len(self.daily_plan)} tasks "
            f"({required_count} required, {optional_count} optional), "
            f"{total_min} min total.",
        ]
        for a, b in self.conflicts:
            lines.append(f"  CONFLICT: '{a.title}' overlaps '{b.title}'")
        return "\n".join(lines)