from dataclasses import dataclass, field
from datetime import date, time as Time
from typing import Optional


@dataclass
class Task:
    """Single pet care activity."""
    task_id: int
    pet_id: int             # links task to a specific Pet
    title: str
    task_type: str          # walk | feeding | meds | grooming | enrichment | appointment
    description: str        # longer detail about the activity
    duration: int           # minutes
    task_date: date
    task_time: Time
    priority: int
    frequency: str = "once" # once | daily | weekly — how often task repeats
    status: str = "pending" # pending | completed | skipped
    notes: str = ""

    def mark_complete(self) -> None:
        """Set status to completed."""
        self.status = "completed"

    def mark_skipped(self) -> None:
        """Set status to skipped."""
        self.status = "skipped"


@dataclass
class Pet:
    """Stores pet profile and owns that pet's task list."""
    pet_id: int
    pet_name: str
    species: str
    breed: str
    pet_dob: date
    weight: float = 0.0
    medical_notes: str = ""
    tasks: list[Task] = field(default_factory=list)

    def get_age(self) -> int:
        """Return pet's age in whole years."""
        today = date.today()
        return (today - self.pet_dob).days // 365

    def get_tasks(self) -> list[Task]:
        """Return all tasks assigned to this pet."""
        return self.tasks


class Owner:
    """Manages multiple pets; aggregates tasks across all of them."""
    def __init__(
        self,
        owner_id: int,
        name: str,
        available_time: int,        # minutes per day
        preferences: Optional[list] = None,
    ):
        self.owner_id = owner_id
        self.name = name
        self.available_time = available_time
        self.preferences: list = preferences or []
        self.pets: list[Pet] = []
        # no self.tasks — tasks live on Pet, Owner aggregates via get_tasks()

    def add_pet(self, pet: Pet) -> None:
        """Add a pet to the owner's pet list."""
        self.pets.append(pet)

    def edit_pet(self, pet_id: int, updates: dict) -> None:
        """Update attributes of an existing pet by ID."""
        pass

    def get_pet(self, pet_id: int) -> Optional[Pet]:
        """Return the pet matching pet_id, or None if not found."""
        return next((p for p in self.pets if p.pet_id == pet_id), None)

    def remove_pet(self, pet_id: int) -> None:
        """Remove a pet from the owner's pet list by ID."""
        self.pets = [p for p in self.pets if p.pet_id != pet_id]

    def add_task(self, task: Task) -> None:
        """Add a task to the correct pet's task list using task.pet_id."""
        pet = self.get_pet(task.pet_id)
        if pet:
            pet.tasks.append(task)

    def edit_task(self, task_id: int, updates: dict) -> None:
        """Update attributes of an existing task by ID."""
        pass

    def remove_task(self, task_id: int) -> None:
        """Remove a task from its pet's task list by ID."""
        pass

    def get_tasks(self) -> list[Task]:
        """Return all tasks across every pet owned."""
        return [task for pet in self.pets for task in pet.tasks]

    def get_schedule(self) -> list[Task]:
        """Return the current daily plan generated by the Scheduler."""
        return []


class Scheduler:
    """Brain: retrieves, organizes, and manages tasks across all pets."""
    def __init__(self, owner: Owner, schedule_date: date):
        self.owner = owner
        self.schedule_date = schedule_date
        self.daily_plan: list[Task] = []

    def get_tasks_for_pet(self, pet_id: int) -> list[Task]:
        """Return all tasks belonging to a single pet."""
        return [t for t in self.owner.get_tasks() if t.pet_id == pet_id]

    def get_tasks_for_date(self, target: date) -> list[Task]:
        """Return all tasks scheduled on a specific date."""
        return [t for t in self.owner.get_tasks() if t.task_date == target]

    def prioritize_tasks(self) -> list[Task]:
        """Sort today's tasks by priority descending, then by time ascending."""
        today_tasks = self.get_tasks_for_date(self.schedule_date)
        return sorted(today_tasks, key=lambda t: (-t.priority, t.task_time))

    def generate_plan(self) -> list[Task]:
        """Fit prioritized tasks into the owner's available_time budget."""
        plan = []
        time_used = 0
        for task in self.prioritize_tasks():
            if time_used + task.duration <= self.owner.available_time:
                plan.append(task)
                time_used += task.duration
        self.daily_plan = plan
        return plan

    def notify(self, message: str) -> None:
        """Send a notification message to the owner."""
        pass

    def explain_plan(self) -> str:
        """Return a human-readable explanation of why the plan was generated."""
        pass
